### ISSUE TITLE
Button padding defaults don't play nicely when only padding is set

### ISSUE THREAD

**Issue by lucastobrazil** [lucastobrazil/cabana-react#1]
In defining the base `Button` component, we set `px` and `py` properties explicitly:

```js
const Button = props => <BaseButton fontSize="small" px={3} py={1} {...props} />;
```

If the user decides to instance `Button` and only set padding as `p`, naturally the props are overridden:

```js
MyButton.defaultProps = {
    extend: Button,
    p: 2,
};
```

```css
.button-12345 {
    padding: 16px; /* overridden by the following properties */
    padding-left: 8px;
    padding-right: 8px;
    padding-top: 16px;
    padding-bottom: 16px;
}
```

We need to set more sensible defaults in the core `Button` component so the user can set it how ever they like.
